<?php
/** A "flash" message dialog, pops up in the layout blade if there is a message.
 * Can be both info message or error message.
 * @param $msg - required - the text message
 * @param $type - optional - 'error' or 'info' - default is 'error'
 * @param $class - optional - any additional CSS classes to apply - default ''
 * @param $title - optional - The title of the dialog. Defaults according to type
 * @param $closetext - optional - The text on the 'Close' button. Default: 'Okay'
 */
if (empty($class)) $class = '';
if (empty($closetext)) $closetext = 'Okay';
if (empty($type) || ($type !== 'info')) {
  $type = 'error';
  $dialogClass = 'error-dialog';
  $defaultTitle = 'Error:';
} else {
  $type = 'info';
  $defaultTitle = 'Notice:';
  $dialogClass = 'info-dialog';
}
if (empty($title)) $title = $defaultTitle;

?>
<div class='js-dialog-content dialog-on-load'
           data-dialog="info-dialog"
           data-title='<?=html_encode($title)?>'
           data-minHeight='300'
           data-closetext='<?=$closetext?>'
     >
      <div class='<?=$dialogClass . ' '.$class?>'>
        <?=$msg?>
      </div>
</div>