<?php
namespace App\References;
use PkExtensions\PkRefManager;
class IndustryRef extends PkRefManager {
  public static $refArr = [
    10 => 'Accountants',
    20 => 'Advertising/PR',
    30 => 'Aerospace, Defense',
    40 => 'Agriculture',
    50 => 'Alcoholic Beverages',
    60 => 'Alternative Energy',
    70 => 'Architectural Services',
    80 => 'Attorneys/Law Firms',
    90 => 'Automotive',
    100 => 'Business Services',
    110 => 'Casinos / Gambling',
    120 => 'Communications/Electronics',
    130 => 'Computer Software',
    140 => 'Construction',
    150 => 'Defense',
    160 => 'Education',
    170 => 'Energy & Natural Resources',
    180 => 'Entertainment Industry',
    190 => 'Environment',
    195 => 'Fashion',
    200 => 'Food & Beverage',
    210 => 'Health',
    220 => 'Hotels, Motels & Tourism',
    230 => 'Insurance',
    240 => 'Internet',
    250 => 'Labor',
    260 => 'Manufacturing, Misc',
    270 => 'Misc Business',
    280 => 'Non-profits',
    290 => 'Pharmaceuticals/Health Products',
    300 => 'Printing & Publishing',
    310 => 'Sports, Equipment & Services',
    320 => 'Real Estate',
    330 => 'Retail Sales',
    340 => 'Telecom Services & Equipment',
    350 => 'Textiles',
    360 => 'Transportation',
    370 => 'Venture Capital',
    380 => 'Waste Management',
      ];
}
