<?php /*
Include this just inside the main container (w. BS)
*/
$route = $route ?? '/auth/login';
?>
<style>
  div.login-register-dialog {

    display: flex;
    flex-grow: 10;
    opacity: 0;
    /*
    position: absolute;
    */
    position: fixed;
    top: 5em;
    margin: auto;
    /*
    width: 100%;
    */
    z-index: 1000;
    /*
    */
    align-items: center;
    justify-content: center;
  }
    /*
    max-width: 600px;
    */
    div.inner-dlg {
    display: flex;
    align-self: center;
    border: solid black 1px;
    border-radius: 5px;
    padding: .5em 0;
    background-color: #aaa ;

    }

  .lr-wrap {
    width: 300px;
    border: #888 solid 1px;
    background-color: #bbb ;
    margin: 2px;
    padding: 2px;
    border-radius: 5px;
    display: flex;
    padding-left: 3px;
    padding-right: 3px;
    padding-bottom: 3px;
    flex-direction: column;
    /*
    justify-content: space-evenly;
    */
    height: 100%;
  }
  .lrdlg-link-wrap {
    text-align: center;
    padding: 1px;
    margin: 1px;
  }
  .flex-between {
    display: flex;
    justify-content: space-between;
  }
  .lrdlg-link {
    font-size: 1.2em;
    text-align: center;
    color: #006;
  }
  .v-space-flex {
    display: flex;
    justify-content: space-evenly;
    flex-direction: column;
  }
  .v-c-flex {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
  }

  .flex-grow {
    flex-grow: 20;
  }
</style>
<script>
$(function () {
  $(document).on('click', function(event) {
    if (!$(event.target).closest('div.login-register-dialog').length &&
      !$(event.target).hasClass("log-reg-pop")) {
      console.log("We think we clicked outside the demo dialog");
      $("div.login-register-dialog").hide();
      return;
    }
  });
  
    $('div.login-register-dialog').hide();
    $('div.login-register-dialog').css('opacity',1);
    $('div.login-register-dialog').on("click hover", function(event) {
      event.stopPropagation();
    });
    
    //$(".log-reg-pop").on("click mouseover hover", function (event) {
    $(".log-reg-pop").on("click  hover", function (event) {

      var $el = $(event.target);

      var $lrd = $el.find('div.login-register-dialog');
      $('div.login-register-dialog').not($lrd.get(0)).hide();
      $lrd.show();
      console.log("Devent to show login reg dialog");
      setundermenu('div.login-register-dialog');
      //setundermenu($lrd);
      $el.find('div.demo-dialog').hide();
      //$('div.login-register-dialog').show();
      $lrd.show();
      console.log("Tried to show reg dlg?");
    });

    $(window).resize(function () {
      setundermenu('div.login-register-dialog');
    });

    $('.lrdlg-cancel-btn').click(function(e) {
      var $e = $(e.target);
      $e.closest('div.login-register-dialog').hide();
    });
});
</script>

<style>
  div.lrdlg-row {
    align-self: stretch;
    text-align: center;
    display: flex;
    justify-content: center;
    
    
  }
  div.lrdlg-col {
    display: flex;
    justify-content: center;
  }
</style>
  <li class="nav-item nav-text log-reg-pop">
<div class="login-register-dialog h-center flex-grow">
  <div class="inner-dlg">
<div class="container-fluid flex-grow">
  <!--
  <div class="flex">
  -->
  <div class="row lrdlg-row">





    <div class=" lrdlg-col">

      <div class="lr-wrap login">
        <div class="shib2"><?=$loginlabel ?? "Login"?></div>
        <div class="v-space-flex full-height p-h-1 p-b-1">
        <form class='dlg-login form' method='POST' action='<?= url($route) ?>' >
<?= csrf_field() ?>
          <div data-tootik="Email">
          <input class='form-control m-b-2' data-tootik="Email" type='text' name='email' placeholder='Email' />
          </div>
          <div data-tootik="Password">
          <input class='form-control m-b-2' data-tootik="Password" type='password' name='password' placeholder='Password' />
          <div>
          </div>
            <div class="flex-between">

              <div class="v-c-flex">
                <div>
                <label class='inline-remember inline' for='remember-inline'>Remember Me?</label>
                <!--
              </div>
              <div class="v-c-flex">
                -->
                <input class='remember-inline form-control auto-width inline checkbox-inline m-l-1' type="checkbox" name="remember">
                </div>
              </div>
              <div class="v-c-flex">
                <button type="submit" class='inline auto-width btn btn-primary form-control'>Login</button>
              </div>

            </div>
            <div>
        <div class="lrdlg-link-wrap">
              <a class="lrdlg-link" href="<?= route('auth_forgotpassword_form'); ?>">Forgot Password?</a>
            </div>
            </div>
          </div>
          </form>
          <div>
          </div>
          </div>
      </div>
    </div>









          <?php if (isset($registerform)) { ?>
    <div class="col-md-6 lrdlg-col">
      <div class="lr-wrap register">
        <div class="shib2">Register/Sign Up</div>
        <div class="v-space-flex full-height p-h-1 p-b-1">
        <div class="lrdlg-link-wrap">
<div class="shir3 tac">Register as a <?=$registerform?></div>
<div class="tac section">
<form method="POST" action="/auth/register">
    <?= csrf_field() ?>
    <table class='pk-table'>
      <tr>
        <td class='pk-lbl'> Name</td>
        <td><input class='pk-inp' type="text" name="name" value="<?= old('name') ?>"></td>
      </tr>
    <tr>
        <td class='pk-lbl'> Email</td>
        <td><input class='pk-inp' type="email" name="email" value="<?= old('email') ?>"></td>
    </tr>
    <tr>
        <td class='pk-lbl'>Password</td>
        <td><input class='pk-inp' type="password" name="password"></td>
    </tr>
    <tr>
        <td class='pk-lbl'>Confirm Password</td>
        <td> <input class='pk-inp' type="password" name="password_confirmation"></td>
    </tr>
    </table>
    <div class='tac'>
        <button type="submit">Register</button>
    </div>
</form>
</div>
      </div>
      </div>
    </div>
          
    </div>
          <?php } ?>

          <?php
           if( Route::has('login_facebook') ) {
             ?>

    <div class="lrdlg-link-wrap">
      <a class="lrdlg-link" href="<?= route('login_facebook') ?>"
          class="btn btn-primary btn-block">
        <img class='tac' style="max-height: 30px;"
              src='<?=asset('/mixed/img/LoginWFacebook.png')?>' /> 
      </a>
    </div>

          <?php
           }
             ?>





  </div>
  <div class="row lrdlg-row">
  <div class="col tac">
  <div class='lrdlg-cancel-row tac m-t-2'><div class='btn btn-primary lrdlg-cancel-btn'>Cancel</div></div>
  </div>
  </div>

</div>
</div>
</div>

<!-- The menu item, so it doesn't need to be also icnluded -->

<?= $menutext ??  "Login/Sign Up"?></li>
`
  <!--
  -->
