<?php /*
Include this just inside the main container (w. BS)
*/
?>
<style>
  div.login-register-dialog {

    display: flex;
    flex-grow: 10;
    opacity: 0;
    position: absolute;
    margin: auto;
    width: 100%;
    /*
    */
    align-items: center;
    justify-content: center;
  }
    /*
    max-width: 600px;
    */
    div.inner-dlg {
    display: flex;
    align-self: center;
    border: solid black 1px;
    border-radius: 5px;
    padding: .5em 0;
    background-color: #aaa ;

    }

  .lr-wrap {
    width: 300px;
    border: #888 solid 1px;
    background-color: #bbb ;
    margin: 2px;
    padding: 2px;
    border-radius: 5px;
    display: flex;
    padding-left: 3px;
    padding-right: 3px;
    padding-bottom: 3px;
    flex-direction: column;
    /*
    justify-content: space-evenly;
    */
    height: 100%;
  }
  .lrdlg-link-wrap {
    text-align: center;
    padding: 1px;
    margin: 1px;
  }
  .flex-between {
    display: flex;
    justify-content: space-between;
  }
  .lrdlg-link {
    font-size: 1.2em;
    text-align: center;
    color: #006;
  }
  .v-space-flex {
    display: flex;
    justify-content: space-evenly;
    flex-direction: column;
  }
  .v-c-flex {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
  }

  .flex-grow {
    flex-grow: 20;
  }
</style>
<script>
$(function () {
    $('div.login-register-dialog').hide();
    $('div.login-register-dialog').css('opacity',1);
    $(".log-reg-pop").on("click hover mouseover", function () {
      setundermenu('div.login-register-dialog');
      $('div.login-register-dialog').show();
    });
    $(window).resize(function () {
      setundermenu('div.login-register-dialog');
    });

    $('.lrdlg-cancel-btn').click(function() {
      $('div.login-register-dialog').hide();
    });
  });
</script>

<style>
  div.lrdlg-row {
    align-self: stretch;
    text-align: center;
    display: flex;
    justify-content: center;
    
    
  }
  div.lrdlg-col {
    display: flex;
    justify-content: center;
  }
</style>
<div class="login-register-dialog h-center flex-grow">
  <div class="inner-dlg">
<div class="container-fluid flex-grow">
  <!--
  <div class="flex">
  -->
  <div class="row lrdlg-row">
    <div class="col-md-6 lrdlg-col">

      <div class="lr-wrap login">
        <div class="shib2">Login</div>
        <div class="v-space-flex full-height p-h-1 p-b-1">
        <form class='dlg-login form' method='POST' action='<?= url('/auth/login') ?>' >
<?= csrf_field() ?>
          <div data-tootik="Email">
          <input class='form-control m-b-2' data-tootik="Email" type='text' name='email' placeholder='Email' />
          </div>
          <div data-tootik="Password">
          <input class='form-control m-b-2' data-tootik="Password" type='password' name='password' placeholder='Password' />
          <div>
          </div>
            <div class="flex-between">

              <div class="v-c-flex">
                <div>
                <label class='inline-remember inline' for='remember-inline'>Remember Me?</label>
                <!--
              </div>
              <div class="v-c-flex">
                -->
                <input class='form-control auto-width inline checkbox-inline m-l-1' type="checkbox" name="remember" id='remember-inline'>
                </div>
              </div>
              <div class="v-c-flex">
                <button type="submit" class='inline auto-width btn btn-primary form-control'>Login</button>
              </div>

            </div>
            <div>
        <div class="lrdlg-link-wrap">
              <a class="lrdlg-link" href="<?= route('auth_forgotpassword_form'); ?>">Forgot Password?</a>
            </div>
            </div>
          </div>
          </form>
          <div>
          </div>
          </div>
      </div>
    </div>
    <div class="col-md-6 lrdlg-col">
      <div class="lr-wrap register">
        <div class="shib2">Register/Sign Up</div>
        <div class="v-space-flex full-height p-h-1 p-b-1">
        <div class="lrdlg-link-wrap">
        <a class="lrdlg-link" href="<?= route('auth_register'); ?>">Register</a>
    </div>

          <?php
           if( Route::has('login_facebook') ) {
             ?>

    <div class="lrdlg-link-wrap">
      <a class="lrdlg-link" href="<?= route('login_facebook') ?>"
          class="btn btn-primary btn-block">
        <img class='tac' style="max-height: 30px;"
              src='<?=asset('/mixed/img/LoginWFacebook.png')?>' /> 
      </a>
    </div>

          <?php
           }
             ?>





      </div>
      </div>
    </div>
  </div>
  <div class="row lrdlg-row">
  <div class="col tac">
  <div class='lrdlg-cancel-row tac m-t-2'><div class='btn btn-primary lrdlg-cancel-btn'>Cancel</div></div>
  </div>
  </div>

</div>
</div>
</div>
  <!--
  -->
